### ISSUE TITLE
bagaimana cara ganti password dan nama user

### ISSUE THREAD

**Issue by gunsmayer** [syauqi/restawrant#1]
bagaimana cara ganti password dan nama user semoga ada tutorial dan update terbaru

**Comment by MangEs23** [comment]
Di restawrant/database/seeders/Admin.php ubah

`public function run()
    {
        User::create([
            'name' => 'Admin',
            'email' => 'admin@gmail.com',
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
            'remember_token' => Str::random(10),
            'is_admin' => 1
        ]);
    }`.  

Ubahlah bagian value dari email dan password 
'email' => 'ubah@gmail.com',
'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',  

Note(password nya di hash dulu)

Setelah itu baru jalankan seeder nya

CMIIW

**Comment by MangEs23** [comment]
Untuk info lengkapnya bisa lihat materi di YouTube tentang database seeders pada Laravel

CMIIW

**Comment by syauqi** [comment]
Terima kasih @MangEs23 sudah bantu aku intinya sih diganti di bagian seeder aja

**Comment by gunsmayer** [comment]
> Untuk info lengkapnya bisa lihat materi di YouTube tentang database seeders pada Laravel
> 
> CMIIW

Makasih mas maklum lagi belajar kwkwkwk biasa di wordpress yg semuanya serba install plugin :)

**Comment by syauqi** [comment]
> > Untuk info lengkapnya bisa lihat materi di YouTube tentang database seeders pada Laravel
> > CMIIW
> 
> Makasih mas maklum lagi belajar kwkwkwk biasa di wordpress yg semuanya serba install plugin :)

Gak papa kok mas, langkah mas buka issues juga sangat tepat. Semangat mas!
